### ISSUE TITLE
Use multiple file datasets

### ISSUE THREAD

**Issue by BenjaminProgram** [karpathy/char-rnn#14]
I have a very big dataset and I was wondering if there is a way to use more than one file in a single training run.

**Comment by karpathy** [comment]
With current code it's not possible. Can you not concatenate the files into a single file?

**Comment by BenjaminProgram** [comment]
Yes, but I am retrieving them from different sources and would like to make it easier.

**Comment by karpathy** [comment]
It's doable you'll just have to write code. Have a look at the loader class - most of the code doesn't know that characters are involved, it's just input indices x and output target indices y.

**Comment by BenjaminProgram** [comment]
I tried to fix it in #18.

**Comment by karpathy** [comment]
I am closing this issue because I don't think this is a critical feature. It's not clear why it's not possible to concatenate the files, and one must have a very large network to take advantage of such large datasets. 
This would also add some code/API complexity because it's not clear to me if there is a nice way to implement this, mostly in terms of the API.
