### ISSUE TITLE
implement sentence in, sentence out network

### ISSUE THREAD

**Issue by culurciello** [karpathy/char-rnn#36]
@karpathy I would like to modify your code to take a piece of a sequence in (say a few words), and only after a specified symbol start outputting a sequence out (say other words).
What is the best way to do this, in your opinion? Thanks for any suggestions and again for the great package!

**Comment by karpathy** [comment]
Hi, this would be somewhat non-trivial with the current code base, but not impossible. You'd have to use a masked loss (to only apply loss on the target part), and you'd have to change quite a bit of the data loader to always provide batches of S,T where S is source and T target.

Closing since this isn't a priority feature for char-rnn.
