### ISSUE TITLE
can we update char-rnn model ?

### ISSUE THREAD

**Issue by saj1919** [karpathy/char-rnn#72]
Thanks for nice blogpost !

It is just a query not an issue ?
Is it possible to update trained model with new data ?
Like continuous learning as humans do ... every day learning new data ... improving vocab and learning how to generate sentences.

**Comment by hughperkins** [comment]
You can do any combination of giving more training examples, and drawing samples.

Note that typically once you've initialized the network, the size is fixed for its lifetime.  That is, its capacity to learn is fixed.  Though I think this sounds like an interesting research direction.

So, anyway, if you make the capacity really big, it will overfit horribly if you just feed it a bit of data.  It will also be really, really slow.  If it's small, then it will stop learning past a certain number of examples, since it's already 'full'.

**Comment by karpathy** [comment]
I think you'd want to use the `initFrom` flag, which lets you initialize network from a previous checkpoint. Then you point it at different data. This should have the effect you're asking about?

**Comment by saj1919** [comment]
Hi, I am new to lua+torch thing so wondering if it could be done. What I was thinking is in terms of python+pickle ... Once I trained model "model_x" with "input_x.txt" (say!). Save the model. Later load the same model and train/update with "input_y.txt". 
Here checkpoints can be considered as model ?
Anyways ... just a thought .. I am going through code though. Thanks !

**Comment by karpathy** [comment]
Yes what you're describing is exactly what `initFrom` would do. The checkpoints contain the model and can be loaded.

**Comment by saj1919** [comment]
Sorry .. may be dumb question ... where can I find "initFrom" ?

**Comment by karpathy** [comment]
it's one of the parameters for `train.lua` ?

**Comment by saj1919** [comment]
Yes .. my bad .. thanks.
